name: Deploy Company Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # REQUIRED for environment secrets

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      # ðŸ” Decode SSH key safely
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > /tmp/id_ed25519
          chmod 600 /tmp/id_ed25519

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key_path: /tmp/id_ed25519
          source: "target/company-0.0.1-SNAPSHOT.jar"
          target: "/home/springapp/production/"
          overwrite: true

      - name: Restart Company service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key_path: /tmp/id_ed25519
          script: |
            sudo systemctl restart companyDemo
            sudo systemctl status companyDemo --no-pager
