name: Deploy Company Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      # ðŸ” Prepare SSH (DEPLOY KEY)
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519_deploy
          chmod 600 ~/.ssh/id_ed25519_deploy
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # ðŸ“¦ Copy JAR
      - name: Copy JAR to server
        run: |
          scp \
            -i ~/.ssh/id_ed25519_deploy \
            -o IdentitiesOnly=yes \
            target/company-0.0.1-SNAPSHOT.jar \
            deploy@${{ secrets.SERVER_IP }}:/home/springapp/production/

      # ðŸ”„ Restart systemd service
      - name: Restart Company service
        run: |
          ssh \
            -i ~/.ssh/id_ed25519_deploy \
            -o IdentitiesOnly=yes \
            deploy@${{ secrets.SERVER_IP }} \
            "sudo -n /usr/bin/systemctl restart companyProd.service"
